spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/grasp
    driver-class-name: org.postgresql.Driver
    username: grasp
    password: grasp
  jpa:
    hibernate:
      ddl-auto: update # When you launch the application for the first time - switch "none" at "create"
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        temp:
          use_jdbc_metadata_defaults: false
          server:
            tomcat:
              connection-timeout: -1
  servlet:
    multipart:
      enabled: true
      max-file-size: 2MB

file:
  path: C:/Users/zoo56/OneDrive/바탕 화면/final-project/src/main/resources/image/

jwt:
  secret:
    key: 7ZWt7ZW0OTntmZTsnbTtjIXtlZzqta3snYTrhIjrqLjshLjqs4TroZzrgpjslYTqsIDsnpDtm4zrpa3tlZzqsJzrsJzsnpDrpbzrp4zrk6TslrTqsIDsnpA=